spring.application.name=ejemplo-external-worker
flowable.external.worker.rest.base-url=http://localhost:7070/flowable-rest
flowable.external.worker.rest.authentication.basic.username=rest-admin
flowable.external.worker.rest.authentication.basic.password=test
flowable.external.worker.rest.context-path=/external-job-api
logging.level.org.flowable=DEBUG
logging.level.org.springframework.boot.autoconfigure=DEBUG